on: [push]
name: immersion
jobs:
  immersion:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - application: ojs
            php-version: 8.3
            database: mysql
          - application: ojs
            php-version: 8.2
            database: mysql
          - application: ojs
            php-version: 8.3
            database: pgsql
          - application: ojs
            php-version: 8.2
            database: pgsql
    name: immersion
    steps:
      - uses: pkp/pkp-github-actions@v1
        with:
         node_version: 20
         branch: 'stable-3_4_0'
         repository: pkp
         plugin: true
